version: '3'
services:
  backend:
    build: backend
    restart: unless-stopped
    volumes:
      - ontobrowser-data:/var/lib/postgresql/data
    env_file:
      - docker-compose.env

  frontend:
    build: frontend
    restart: unless-stopped
    env_file:
      - docker-compose.env
    ports:
      - 8080:8080
      - 9990:9990

volumes:
  ontobrowser-data:
